version: 2

sources:
  - name: raw
    tables:
    - name: dbt_orders
      external:
        location: "@public.my_s3/module6/data_cleansing/"
        file_format: "public.module6_csv"
        infer_schema: true